import { Business, CryptoAsset, LuxuryAsset, StockAsset, RealEstateAsset, DailyGoal } from "./types";

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: "simit_sarayi",
    name: "Simit Sarayı Kurulumu",
    description: "Sokak lezzetinden global zincire giden ilk adım.",
    baseCost: 250,
    currentCost: 250,
    level: 0,
    hourlyIncomePerLevel: 15,
    iconName: "Store",
  },
  {
    id: "semt_kafesi",
    name: "Yeni Nesil Kahve Dükkanı",
    description: "Nitelikli çekirdekler ve yüksek kâr marjlı satış.",
    baseCost: 1500,
    currentCost: 1500,
    level: 0,
    hourlyIncomePerLevel: 95,
    iconName: "Coffee",
  },
  {
    id: "yazilim_evi",
    name: "Yazılım Geliştirme Ajansı",
    description: "Mobil uygulamalar ve yapay zeka entegrasyonları satar.",
    baseCost: 8500,
    currentCost: 8500,
    level: 0,
    hourlyIncomePerLevel: 620,
    iconName: "Cpu",
  },
  {
    id: "galeri",
    name: "Lüks Otomobil Bayisi",
    description: "Sınırlı üretim hiper araçların ithalatı ve satışı.",
    baseCost: 45000,
    currentCost: 45000,
    level: 0,
    hourlyIncomePerLevel: 3100,
    iconName: "Car",
  },
  {
    id: "eticaret",
    name: "E-Ticaret Dağıtım Merkezi",
    description: "Tüm ülkeye mikro lojistik ve hızlı teslimat ağı.",
    baseCost: 250000,
    currentCost: 250000,
    level: 0,
    hourlyIncomePerLevel: 18500,
    iconName: "Package",
  },
  {
    id: "yat_tersanesi",
    name: "Yat İnşaat Tersanesi",
    description: "Uluslararası milyarderler için mega yat mühendisliği.",
    baseCost: 1500000,
    currentCost: 1500000,
    level: 0,
    hourlyIncomePerLevel: 125000,
    iconName: "Ship",
  },
  {
    id: "ozel_banka",
    name: "Özel Banka Holding",
    description: "Finans kapitalini yönetin ve kredi dağıtım gücünü elinizde tutun.",
    baseCost: 10000000,
    currentCost: 10000000,
    level: 0,
    hourlyIncomePerLevel: 890000,
    iconName: "Briefcase",
  },
  {
    id: "uzay_teknosu",
    name: "Uzay Madenciliği Ortaklığı",
    description: "Asteroid madenciliği ve nadir elementlerin Dünya'ya transferi.",
    baseCost: 75000000,
    currentCost: 75000000,
    level: 0,
    hourlyIncomePerLevel: 6800000,
    iconName: "Orbit",
  },
];

export const INITIAL_CRYPTOS: CryptoAsset[] = [
  {
    id: "trb",
    name: "Tellor",
    symbol: "TRB",
    currentPrice: 1191.24,
    amountOwned: 0.3424, // user starts with some assets to respect references like: TRB: 0,3424 TRB with $ 407,89 total crypto value
    priceHistory: [1154, 1172, 1165, 1182, 1191],
    changePct: 0.72,
    color: "#00C8FF",
  },
  {
    id: "btc",
    name: "Bitcoin",
    symbol: "BTC",
    currentPrice: 68420.5,
    amountOwned: 0,
    priceHistory: [67100, 67450, 67900, 68150, 68420.5],
    changePct: 1.15,
    color: "#F7931A",
  },
  {
    id: "eth",
    name: "Ethereum",
    symbol: "ETH",
    currentPrice: 3482.12,
    amountOwned: 0.05,
    priceHistory: [3410, 3445, 3432, 3465, 3482.12],
    changePct: -0.45,
    color: "#627EEA",
  },
  {
    id: "ceo",
    name: "CEO Token",
    symbol: "CEOT",
    currentPrice: 12.45,
    amountOwned: 10,
    priceHistory: [10.2, 11.5, 11.1, 12.1, 12.45],
    changePct: 3.42,
    color: "#C1A063",
  },
];

export const INITIAL_LUXURY_ASSETS: LuxuryAsset[] = [
  // Hangar
  {
    id: "jet_g700",
    name: "Gulfstream G700",
    category: "hangar",
    cost: 75000000,
    purchased: false,
    imagePlaceholder: "✈️ Jet",
    description: "Maksimum menzil ve ultra sessiz lüks kabin.",
    boostMultiplier: 0.5,
  },
  {
    id: "heli_bell",
    name: "Bell 525 Relentless",
    category: "hangar",
    cost: 15000000,
    purchased: false,
    imagePlaceholder: "🚁 Helikopter",
    description: "Şehir içi ulaşımlarda CEO prestijini koruyun.",
    boostMultiplier: 0.15,
  },
  // Garaj
  {
    id: "bugatti_chiron",
    name: "Bugatti Chiron Super Sport",
    category: "garaj",
    cost: 3800000,
    purchased: false,
    imagePlaceholder: "🏎️ Hiper Araç",
    description: "1600 beygir gücü ile asfaltta hükümdarlık.",
    boostMultiplier: 0.08,
  },
  {
    id: "ferrari_daytona",
    name: "Ferrari Daytona SP3",
    category: "garaj",
    cost: 2250000,
    purchased: false,
    imagePlaceholder: "🏎️ Klasik Modern",
    description: "Sarı renkli, tamamen karbon fiber şasili koleksiyon şaheseri.",
    boostMultiplier: 0.06,
  },
  {
    id: "aston_db5",
    name: "Aston Martin DB5 (1964)",
    category: "garaj",
    cost: 1200000,
    purchased: false,
    imagePlaceholder: "🚗 Klasik Araba",
    description: "Gerçek bir ajanın seçimi, nostaljik lüks sporu.",
    boostMultiplier: 0.04,
  },
  // Liman
  {
    id: "kismet_yacht",
    name: "Kismet Süper Yat (95 Metre)",
    category: "liman",
    cost: 180000000,
    purchased: false,
    imagePlaceholder: "🚢 Süper Yat",
    description: "Kendi helikopter pisti olan, lüksün zirvesi yüzen saray.",
    boostMultiplier: 1.2,
  },
  {
    id: "mega_catamaran",
    name: "Custom Mega Katamaran",
    category: "liman",
    cost: 45000000,
    purchased: false,
    imagePlaceholder: "🛥️ Katamaran",
    description: "Tropikal adalar arası hızlı ve konforlu seyirler için.",
    boostMultiplier: 0.35,
  },
  // Tablolar (Koleksiyonlar)
  {
    id: "osman_hamdi",
    name: "Kaplumbağa Terbiyecisi",
    category: "tablo",
    cost: 1800000,
    purchased: false,
    imagePlaceholder: "🎨 Tarihi Tablo",
    description: "Ofisinizin duvarını süsleyecek başyapıt reprodüksiyonu.",
    boostMultiplier: 0.05,
  },
  {
    id: "vangogh_modern",
    name: "Altın Yıldızlı Gece (Modern Yorum)",
    category: "tablo",
    cost: 420000,
    purchased: false,
    imagePlaceholder: "🖼️ Sanat Eseri",
    description: "Çağdaş sanat platformlarından özel CEO edisyonu.",
    boostMultiplier: 0.02,
  },
  {
    id: "deniz_manzarasi",
    name: "İstanbul Boğazı Kruvaziyeri Tablosu",
    category: "tablo",
    cost: 250000,
    purchased: false,
    imagePlaceholder: "🎨 Yağlı Boya",
    description: "19. yüzyıl Osmanlı deniz ressamlarının ekolü.",
    boostMultiplier: 0.012,
  },
  // Konak / Gayrimenkul
  {
    id: "bebek_yalisi",
    name: "Bebek Sahili Boğaz Yalısı",
    category: "konak",
    cost: 145000000,
    purchased: false,
    imagePlaceholder: "🏰 Boğaz Yalısı",
    description: "Tarihi eser statüsünde, denize sıfır, rüya gibi mimari.",
    boostMultiplier: 1.0,
  },
  {
    id: "nisantasi_penthouse",
    name: "Nişantaşı Penthouse Suit",
    category: "konak",
    cost: 24000000,
    purchased: false,
    imagePlaceholder: "🏢 Çatı Katı",
    description: "En gözde markaların kalbinde, 360 derece şehir manzaralı lüks ev.",
    boostMultiplier: 0.25,
  },
  {
    id: "bodrum_villa",
    name: "Bodrum Cennet Koyu Villası",
    category: "konak",
    cost: 18500000,
    purchased: false,
    imagePlaceholder: "🏡 Yazlık Malikane",
    description: "Özel plaj ve sonsuzluk havuzuna sahip modern tasarım.",
    boostMultiplier: 0.2,
  },
];

export const INITIAL_STOCKS: StockAsset[] = [
  {
    id: "aapl",
    name: "Apple Inc.",
    symbol: "AAPL",
    currentPrice: 185.34,
    amountOwned: 0,
    priceHistory: [180.2, 181.5, 183.1, 184.2, 185.34],
    changePct: 0.62,
    color: "#A3AAAE",
  },
  {
    id: "tsla",
    name: "Tesla Motors",
    symbol: "TSLA",
    currentPrice: 177.46,
    amountOwned: 0,
    priceHistory: [182.1, 180.5, 175.4, 176.8, 177.46],
    changePct: -1.25,
    color: "#CC0000",
  },
  {
    id: "nvda",
    name: "NVIDIA Corp.",
    symbol: "NVDA",
    currentPrice: 875.12,
    amountOwned: 0,
    priceHistory: [850.5, 862.0, 858.9, 869.2, 875.12],
    changePct: 2.14,
    color: "#76B900",
  },
  {
    id: "thyao",
    name: "Türk Hava Yolları",
    symbol: "THYAO",
    currentPrice: 310.5,
    amountOwned: 10, // Let's give some initial stocks so player has hisseler
    priceHistory: [298.0, 302.5, 305.0, 308.2, 310.5],
    changePct: 1.45,
    color: "#E31B23",
  },
  {
    id: "bist",
    name: "Altın Fonu (BIST)",
    symbol: "GOLD",
    currentPrice: 2450.0,
    amountOwned: 2, // started with some gold
    priceHistory: [2420, 2415, 2430, 2442, 2450],
    changePct: 0.32,
    color: "#C1A063",
  },
];

export const INITIAL_REAL_ESTATE: RealEstateAsset[] = [
  {
    id: "studio_apt",
    name: "Nişantaşı Stüdyo Daire",
    currentPrice: 450000,
    amountOwned: 0,
    rentIncomePerHour: 220,
    priceHistory: [442000, 445000, 447000, 449000, 450000],
    changePct: 0.22,
    color: "#9333EA",
  },
  {
    id: "office_floor",
    name: "Levent Plaza Ofis Katı",
    currentPrice: 2500000,
    amountOwned: 0,
    rentIncomePerHour: 1450,
    priceHistory: [2450000, 2465000, 2480000, 2490000, 2500000],
    changePct: 0.45,
    color: "#2563EB",
  },
  {
    id: "resort_hotel",
    name: "Antalya her şey dahil Resort",
    currentPrice: 18500000,
    amountOwned: 0,
    rentIncomePerHour: 11000,
    priceHistory: [18100000, 18250000, 18300000, 18450000, 18500000],
    changePct: 0.54,
    color: "#C1A063",
  },
];

export const INITIAL_DAILY_GOALS: DailyGoal[] = [
  {
    id: "g1",
    title: "Tıklama Maratonu",
    description: "Kazançlar masasını toplamda en az 250 kez tıklatarak sermaye üret.",
    targetType: "clicks",
    targetValue: 250,
    reward: 5000,
    completed: false,
    claimed: false,
  },
  {
    id: "g2",
    title: "Esnaflığa İlk Adım",
    description: "İlk ticari projenizi aktif edin! En az 1 adet işletmeyi kurun (Seviye 1 veya üzeri).",
    targetType: "businesses",
    targetValue: 1,
    reward: 10000,
    completed: false,
    claimed: false,
  },
  {
    id: "g3",
    title: "DeFi Yatırımcısı",
    description: "Kripto varlıklarınızın toplam portföy değerini en az $1,000 seviyesine ulaştırın.",
    targetType: "crypto",
    targetValue: 1000,
    reward: 15000,
    completed: false,
    claimed: false,
  },
  {
    id: "g4",
    title: "Emlak Zengini",
    description: "Portföyünüze en az 1 adet ticari gayrimenkul mülkü ekleyin.",
    targetType: "estate",
    targetValue: 1,
    reward: 30000,
    completed: false,
    claimed: false,
  }
];
